kind: pipeline
name: release

platform:
  os: linux
  arch: amd64

steps:
  - name: release
    image: node:16.5
    commands:
      - npm install -g semantic-release@~17.4.4 @semantic-release/exec@v5.0.0
      - semantic-release
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      event:
        exclude:
          - tag
