name: Release

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout with token
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Checkout without token
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2.3.4

      - name: Release
        if: github.event_name != 'pull_request'
        uses: cycjimmy/semantic-release-action@v2.5.4
        with:
          semantic_version: 17.4
          extra_plugins: |
            @semantic-release/exec@v5
        env:
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
